CREATE TABLE IF NOT EXISTS TABLE_NAME (
	rownum INTEGER,
    sourced INTEGER NOT NULL DEFAULT 0 CHECK (sourced IN (0, 1)),
    placed INTEGER NOT NULL DEFAULT 0 CHECK (placed IN (0, 1)),
    comp_ref TEXT,
    vendor TEXT NOT NULL,
    vendor_part_number TEXT NOT NULL,
    comp_value TEXT,
    partnumber TEXT,
    description TEXT,
    comment TEXT,
    footprint TEXT,
    price_per_part REAL,
    parts_per_sales_unit INTEGER,
    manufacturer TEXT,
    manufacturer_part_number TEXT,
    mate_manufacturer TEXT,
    mate_manufacturer_part_number TEXT,
    mate_vendor TEXT,
    mate_vendor_part_number TEXT,
    mate_price_per_part REAL,
    mate_parts_per_sales_unit INTEGER,
    box_id INTEGER,
    box_row INTEGER,
    box_column INTEGER,
    quantity INTEGER,
    PRIMARY KEY (vendor, vendor_part_number)
);
